.PHONY: tidy test build run exec clean

APP_NAME := fizzbuzz-api
BIN_DIR  := bin
PKG      := ./...

tidy:
	go mod tidy

build:
	go build -o $(BIN_DIR)/$(APP_NAME) ./cmd/api

test:
	go test $(PKG)

run:
	go run ./cmd/api

exec: build
	$(BIN_DIR)/$(APP_NAME)